version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    environment:
      - PORT=4000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
